---

- name: Example copying script file
  template:
    src: files/dockerfiles/Dockerfile.j2
    dest: ./Dockerfile

# Build
- name: Build image and with build args
  docker_image:
    name: cloud-sdk:custom
    build:
      path: ./
      dockerfile: Dockerfile
      pull: yes
    source: build

- name: Create a gcloud config
  docker_container:
    name: gcloud-config
    image: cloud-sdk:custom
    command: ["gcloud auth activate-service-account --key-file=/tmp/{{custom_vars[2].serviceaccounts[0].json_name}}"]

- name: Describe cloudsql
  docker_container:
    name: cloud-sdk-latest-cloudsql-describe
    image: cloud-sdk:custom
    auto_remove: no
    command: ["gcloud sql instances describe {{custom_vars[8].cloudsql[0].instance_name}}"]
    volumes_from:
      - gcloud-config

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Get infos on container
  shell: docker logs cloud-sdk-latest-cloudsql-describe | grep -i serviceAccountEmailAddress
  become: yes
  register: sql_sa

- name: Grant the desire access(storage.objectAdmin) level to the bucket
  docker_container:
    name: cloud-sdk-latest-cloudsql-bucket-acl
    image: cloud-sdk:custom
    auto_remove: no
    command: ["gsutil iam ch serviceAccount:{{ sql_sa.stdout_lines[0] | regex_replace('(.*): ') }}:objectAdmin gs://{{custom_vars[8].cloudsql[0].properties[0].dump_bucket}}"]
    volumes_from:
      - gcloud-config

- name: Clean up Dockerfile
  file:
    path: ./Dockerfile
    state: absent

- name: Clean up container
  docker_container:
    name: "{{item}}"
    state: absent
  with_items:
    - cloud-sdk-latest-cloudsql-describe
    - cloud-sdk-latest-cloudsql-bucket-acl
    - gcloud-config

- name: Clean up images
  docker_image:
    state: absent
    name: "{{item.name}}"
    tag: "{{item.tag}}"
  with_items:
    - { name: cloud-sdk, tag: custom }